from odoo import Command, api, fields, models, _
from odoo.exceptions import UserError
from odoo.tools.sql import index_exists


class AccountMove(models.Model):
    _inherit = 'account.move'

    amc_id = fields.Many2one('amc.contract', string='Mother AMC',
                             index=True, copy=False, ondelete='set null')
    amc_po_id = fields.Many2one('purchase.order', string='AMC Purchase Order',
                                index=True, copy=False, ondelete='set null')
    amc_site_id = fields.Many2one('amc.site', string='AMC Site', copy=False, ondelete='set null')

    # -- vendor bill fields -----------------------------------------------------
    amc_period_ids = fields.Many2many('amc.contract', 'amc_period_account_move_rel',
                                      'move_id', 'amc_period_id', string='AMC Service Periods',
                                      copy=False)
    amc_milestone_number = fields.Integer(string='AMC Payment Milestone', copy=False)
    amc_quarter_id = fields.Many2one('amc.contract', string='AMC Quarter',
                                     index=True, copy=False, ondelete='set null',
                                     domain="[('parent_amc_id', '!=', False)]",
                                     help='Service period this bill is raised for. A quarterly AMC '
                                          'bills one period per quarter, so this reads back as the '
                                          'quarter the bill covers.')
    amc_milestone_label = fields.Char(string='AMC Milestone', compute='_compute_amc_milestone_label',
                                      store=True)
    amc_is_advance = fields.Boolean(string='AMC Advance Bill', copy=False)
    amc_remarks = fields.Text(string='AMC Remarks', copy=False)
    amc_service_report_ids = fields.Many2many(
        'ir.attachment', 'amc_bill_service_report_rel', 'move_id', 'attachment_id',
        string='Service Reports to Attach', copy=False,
        help='Service report documents copied from the AMC service periods selected '
             'when this bill was created.')
    amc_service_report_count = fields.Integer(compute='_compute_amc_service_report_count')

    # -- provision entry fields -------------------------------------------------
    amc_provision_type = fields.Selection([
        ('regular', 'Regular'),
        ('catchup', 'Catch-Up'),
        ('reversal', 'Reversal'),
    ], string='AMC Provision Type', copy=False, index=True,
        help='Set on the journal entries generated by AMC provisioning.')
    amc_provision_month = fields.Date(string='Provisioned Month', copy=False,
                                      help='First day of the month this provision covers.')
    amc_provision_month_name = fields.Char(string='Period', compute='_compute_amc_provision_month_name',
                                           store=True)
    amc_service_period_id = fields.Many2one('amc.contract', string='AMC Service Period',
                                            copy=False, ondelete='set null',
                                            help='Set on reversal entries only.')
    amc_provision_amount = fields.Monetary(string='Provision Amount', currency_field='company_currency_id',
                                           compute='_compute_amc_provision_amount', store=True)
    amc_contract_ids = fields.Many2many('amc.contract', 'amc_move_contract_rel',
                                        'move_id', 'amc_id', string='Covered AMCs',
                                        compute='_compute_amc_contract_ids', store=True,
                                        help='Every Mother AMC with a line on this entry. An order '
                                             'covering several sites yields one consolidated entry '
                                             'per month.')

    def init(self):
        """One order = one provision entry per month.

        Reversals are per service period and can legitimately repeat inside a month,
        so they are excluded from the unique index.
        """
        super().init()
        if not index_exists(self.env.cr, 'account_move_amc_provision_po_month_uniq'):
            self.env.cr.execute("""
                CREATE UNIQUE INDEX account_move_amc_provision_po_month_uniq
                ON account_move (amc_po_id, amc_provision_month)
                WHERE amc_provision_type IN ('regular', 'catchup')
            """)

    @api.depends('amc_milestone_number')
    def _compute_amc_milestone_label(self):
        for move in self:
            move.amc_milestone_label = 'Q%s' % move.amc_milestone_number if move.amc_milestone_number else False

    @api.depends('amc_service_report_ids')
    def _compute_amc_service_report_count(self):
        for move in self:
            move.amc_service_report_count = len(move.amc_service_report_ids)

    @api.depends('amc_provision_month')
    def _compute_amc_provision_month_name(self):
        for move in self:
            move.amc_provision_month_name = move.amc_provision_month.strftime('%b %Y') \
                if move.amc_provision_month else False

    @api.depends('amc_provision_type', 'line_ids.debit')
    def _compute_amc_provision_amount(self):
        for move in self:
            move.amc_provision_amount = sum(move.line_ids.mapped('debit')) \
                if move.amc_provision_type else 0.0

    @api.depends('amc_provision_type', 'line_ids.amc_id')
    def _compute_amc_contract_ids(self):
        for move in self:
            contracts = move.line_ids.mapped('amc_id') if move.amc_provision_type \
                else self.env['amc.contract']
            move.amc_contract_ids = [Command.set(contracts.ids)]

    def action_view_amc_service_reports(self):
        """Open the service report documents tagged onto this bill (read-only)."""
        self.ensure_one()
        return {
            'name': _('Service Reports to Attach'),
            'type': 'ir.actions.act_window',
            'res_model': 'ir.attachment',
            'view_mode': 'kanban',
            'views': [(self.env.ref('amc_management.view_amc_service_report_kanban').id, 'kanban')],
            'domain': [('id', 'in', self.amc_service_report_ids.ids)],
            'context': {'create': False, 'edit': False, 'delete': False},
        }

    # ------------------------------------------------------------------
    # AMC provisioning
    # ------------------------------------------------------------------

    @api.model
    def _get_amc_journal(self):
        """Return the journal used for AMC provision and reversal entries.

        Neither the provision nor the expense account is company-wide: both come from
        the product on each contract's purchase line, see ``_amc_provision_account``
        and ``_amc_expense_account`` on the contract.
        """
        params = self.env['ir.config_parameter'].sudo()
        journal_id = params.get_param('amc_management.provision_journal_id')

        journal = self.env['account.journal'].browse(int(journal_id)).exists() if journal_id else False
        if not journal:
            journal = self.env['account.journal'].search(
                [('type', '=', 'general'), ('company_id', '=', self.env.company.id)], limit=1)
            if not journal:
                raise UserError(_("No miscellaneous journal is available to book AMC provisions."))
        return journal

    @api.model
    def _prepare_amc_provision_vals(self, po, reference, provision_type, month, accounting_date,
                                    contract_amounts):
        """Build a draft AMC provision entry.

        ``contract_amounts`` maps each Mother AMC to its share of the month, giving one
        debit and one credit line per site. Dr AMC Expense / Cr AMC Provision; a
        reversal flips the pair. Both accounts are resolved per contract from its
        product's category, so an order covering sites bought under different
        products or categories books each one to its own accounts.

        The site sits on the entry header, which is single-valued, so it is only
        filled when every contract on the entry points at the same site -- an order
        spanning several sites leaves it empty rather than picking one arbitrarily.
        Each line still carries its own site's analytic distribution.

        Both lines carry the accounting date as their due date. A provision touches no
        payable account, so nothing computes one otherwise and the Due Date column
        would sit empty.

        Read as sudo throughout: the users driving this workflow need not hold
        accounting access, and these are system-generated bookkeeping records.
        """
        self = self.sudo()
        po = po.sudo()
        contract_amounts = {contract.sudo(): amount for contract, amount in contract_amounts.items()}
        journal = self._get_amc_journal()
        contracts = self.env['amc.contract'].sudo().union(*contract_amounts)
        contracts._amc_check_expense_accounts()
        contracts._amc_check_provision_accounts()

        sites = [contract._amc_site() for contract in contracts]
        site = sites[0] if sites and all(one == sites[0] for one in sites) else self.env['amc.site']

        move_lines = []
        for contract, amount in contract_amounts.items():
            expense_account = contract._amc_expense_account()
            provision_account = contract._amc_provision_account()
            if provision_type == 'reversal':
                debit_account, credit_account = provision_account, expense_account
            else:
                debit_account, credit_account = expense_account, provision_account
            contract_site = contract._amc_site()
            label = '%s - %s' % (reference, contract_site.name or contract.name or '')
            distribution = contract_site._amc_analytic_distribution() if contract_site else {}
            common = {
                'name': label,
                'partner_id': po.partner_id.id,
                'amc_id': contract.id,
                'amc_site_id': contract_site.id or False,
                'analytic_distribution': distribution or False,
                'date': accounting_date,
            }
            move_lines.append(Command.create(dict(
                common, account_id=debit_account.id, debit=amount, credit=0.0)))
            move_lines.append(Command.create(dict(
                common, account_id=credit_account.id, debit=0.0, credit=amount)))
        return {
            'move_type': 'entry',
            'journal_id': journal.id,
            'date': accounting_date,
            'invoice_date_due': accounting_date,
            'ref': reference,
            'company_id': po.company_id.id,
            'amc_site_id': site.id or False,
            'amc_po_id': po.id,
            'amc_id': list(contract_amounts)[0].id,
            'amc_provision_type': provision_type,
            'amc_provision_month': month,
            'line_ids': move_lines,
        }

    @api.model
    def _amc_provision_domain(self, contract=None, po=None):
        """Domain selecting AMC provision entries, optionally for one contract or order."""
        domain = [('amc_provision_type', '!=', False)]
        if contract is not None:
            domain += ['|', ('amc_id', '=', contract.id), ('line_ids.amc_id', '=', contract.id)]
        if po is not None:
            domain += [('amc_po_id', '=', po.id)]
        return domain


class AccountMoveLine(models.Model):
    _inherit = 'account.move.line'

    amc_id = fields.Many2one('amc.contract', string='Mother AMC',
                             index=True, copy=False, ondelete='set null',
                             help='Set on AMC provision entry lines to tie each site line '
                                  'back to its contract.')
    amc_site_id = fields.Many2one('amc.site', string='AMC Site', copy=False, ondelete='set null')
