from odoo import api, fields, models


class LotRecallReport(models.Model):
    _name = 'lot.recall.report'
    _description = 'Lot Recall Report'
    _order = 'generated_on desc, id desc'
    _inherit = ['mail.thread']

    name = fields.Char(
        string='Reference', required=True, copy=False, readonly=True,
        default=lambda self: self.env['ir.sequence'].next_by_code(
            'lot.recall.report') or 'New')
    lot_ids = fields.Many2many(
        'stock.lot', string='Lots/Serial Numbers', required=True,
        tracking=True,
        help='One or more lots/serial numbers to trace. Select several to '
             'generate one consolidated report, e.g. for a full production run.')
    direction = fields.Selection([
        ('forward', 'Forward only'),
        ('backward', 'Backward only'),
        ('both', 'Both directions'),
    ], string='Trace Direction', required=True, default='both', tracking=True)
    state = fields.Selection([
        ('draft', 'Draft'),
        ('generated', 'Generated'),
    ], default='draft', copy=False, tracking=True)
    generated_by = fields.Many2one(
        'res.users', string='Generated By', readonly=True, copy=False)
    generated_on = fields.Datetime(
        string='Generated On', readonly=True, copy=False)
    company_id = fields.Many2one(
        'res.company', string='Company',
        default=lambda self: self.env.company)

    recall_line_ids = fields.One2many(
        'lot.recall.report.line', 'report_id', string='Recall Lines',
        copy=False)
    forward_line_ids = fields.One2many(
        'lot.recall.report.line', 'report_id', string='Forward Trace Lines',
        domain=[('direction', '=', 'forward')], copy=False)
    backward_line_ids = fields.One2many(
        'lot.recall.report.line', 'report_id', string='Backward Trace Lines',
        domain=[('direction', '=', 'backward')], copy=False)

    forward_customer_count = fields.Integer(
        compute='_compute_forward_stats', string='Customers')
    forward_sale_order_count = fields.Integer(
        compute='_compute_forward_stats', string='Sales Orders')
    forward_delivery_count = fields.Integer(
        compute='_compute_forward_stats', string='Deliveries')
    forward_quantity = fields.Float(
        compute='_compute_forward_stats', string='Affected Quantity (Forward)')

    backward_vendor_count = fields.Integer(
        compute='_compute_backward_stats', string='Vendors')
    backward_purchase_order_count = fields.Integer(
        compute='_compute_backward_stats', string='Purchase Orders')
    backward_production_count = fields.Integer(
        compute='_compute_backward_stats', string='Manufacturing Orders')
    backward_quantity = fields.Float(
        compute='_compute_backward_stats', string='Affected Quantity (Backward)')

    fully_traceable = fields.Boolean(
        compute='_compute_fully_traceable', string='Fully Traceable')
    notify_partner_ids = fields.Many2many(
        'res.partner', compute='_compute_notify_partner_ids',
        string='Affected Customers to Notify')

    @api.depends('recall_line_ids', 'recall_line_ids.partner_id',
                 'recall_line_ids.sale_order_id', 'recall_line_ids.delivery_id',
                 'recall_line_ids.quantity', 'recall_line_ids.direction')
    def _compute_forward_stats(self):
        for report in self:
            lines = report.recall_line_ids.filtered(lambda l: l.direction == 'forward')
            report.forward_customer_count = len(lines.partner_id)
            report.forward_sale_order_count = len(lines.sale_order_id)
            report.forward_delivery_count = len(lines.delivery_id)
            report.forward_quantity = sum(lines.mapped('quantity'))

    @api.depends('recall_line_ids', 'recall_line_ids.partner_id',
                 'recall_line_ids.purchase_order_id', 'recall_line_ids.production_id',
                 'recall_line_ids.quantity', 'recall_line_ids.direction')
    def _compute_backward_stats(self):
        for report in self:
            lines = report.recall_line_ids.filtered(lambda l: l.direction == 'backward')
            report.backward_vendor_count = len(lines.filtered('partner_id').partner_id)
            report.backward_purchase_order_count = len(lines.purchase_order_id)
            report.backward_production_count = len(lines.production_id)
            report.backward_quantity = sum(lines.mapped('quantity'))

    @api.depends('state', 'direction', 'forward_line_ids', 'backward_line_ids')
    def _compute_fully_traceable(self):
        for report in self:
            if report.state != 'generated':
                report.fully_traceable = False
                continue
            ok = True
            if report.direction in ('forward', 'both') and not report.forward_line_ids:
                ok = False
            if report.direction in ('backward', 'both') and not report.backward_line_ids:
                ok = False
            report.fully_traceable = ok

    @api.depends('forward_line_ids.partner_id')
    def _compute_notify_partner_ids(self):
        for report in self:
            report.notify_partner_ids = report.forward_line_ids.partner_id

    def action_generate(self):
        """Compute the forward/backward traceability lines for all selected
        lots using the same stock.move.line data as Inventory > Traceability,
        then persist them on the report for printing and future audit."""
        Line = self.env['lot.recall.report.line']
        for report in self:
            report.recall_line_ids.unlink()
            values = []
            for lot in report.lot_ids:
                if report.direction in ('forward', 'both'):
                    values += report._build_forward_lines(lot)
                if report.direction in ('backward', 'both'):
                    values += report._build_backward_lines(lot)
            Line.create(values)
            report.write({
                'state': 'generated',
                'generated_by': self.env.uid,
                'generated_on': fields.Datetime.now(),
            })
        return True

    def action_reset_draft(self):
        self.write({'state': 'draft'})

    def _build_forward_lines(self, lot):
        """Every outgoing (customer) delivery that shipped this lot."""
        move_lines = self.env['stock.move.line'].search([
            ('lot_id', '=', lot.id),
            ('state', '=', 'done'),
            ('picking_id.picking_type_id.code', '=', 'outgoing'),
        ])
        grouped = {}
        for ml in move_lines:
            picking = ml.picking_id
            sale_order = ml.move_id.sale_line_id.order_id or picking.sale_id
            key = (picking.id, sale_order.id, picking.partner_id.id, ml.product_id.id)
            qty = ml.qty_done if 'qty_done' in ml._fields and ml.qty_done else ml.quantity
            if key not in grouped:
                grouped[key] = {
                    'report_id': self.id,
                    'lot_id': lot.id,
                    'direction': 'forward',
                    'source_type': 'sale',
                    'partner_id': picking.partner_id.id,
                    'sale_order_id': sale_order.id or False,
                    'delivery_id': picking.id,
                    'product_id': ml.product_id.id,
                    'quantity': 0.0,
                    'uom_id': ml.product_uom_id.id,
                    'delivery_date': picking.date_done or picking.date,
                }
            grouped[key]['quantity'] += qty
        return list(grouped.values())

    def _build_backward_lines(self, lot):
        """Vendor receipts and/or the manufacturing order that fed this lot,
        plus one level of component lots when the lot was manufactured."""
        lines = []
        move_lines = self.env['stock.move.line'].search([
            ('lot_id', '=', lot.id),
            ('state', '=', 'done'),
            ('picking_id.picking_type_id.code', '=', 'incoming'),
        ])
        grouped = {}
        for ml in move_lines:
            picking = ml.picking_id
            purchase_order = ml.move_id.purchase_line_id.order_id
            key = (picking.id, purchase_order.id, picking.partner_id.id, ml.product_id.id)
            qty = ml.qty_done if 'qty_done' in ml._fields and ml.qty_done else ml.quantity
            if key not in grouped:
                grouped[key] = {
                    'report_id': self.id,
                    'lot_id': lot.id,
                    'direction': 'backward',
                    'source_type': 'purchase',
                    'partner_id': picking.partner_id.id,
                    'purchase_order_id': purchase_order.id or False,
                    'delivery_id': picking.id,
                    'product_id': ml.product_id.id,
                    'quantity': 0.0,
                    'uom_id': ml.product_uom_id.id,
                    'delivery_date': picking.date_done or picking.date,
                }
            grouped[key]['quantity'] += qty
        lines += list(grouped.values())

        productions = self.env['mrp.production'].search([
            ('lot_producing_ids', 'in', lot.id),
            ('state', '=', 'done'),
        ])
        for production in productions:
            lines.append({
                'report_id': self.id,
                'lot_id': lot.id,
                'direction': 'backward',
                'source_type': 'manufacturing',
                'production_id': production.id,
                'product_id': production.product_id.id,
                'quantity': production.qty_produced or production.product_qty,
                'uom_id': production.product_uom_id.id,
                'delivery_date': production.date_finished,
            })
            component_move_lines = production.move_raw_ids.move_line_ids.filtered('lot_id')
            for cml in component_move_lines:
                qty = cml.qty_done if 'qty_done' in cml._fields and cml.qty_done else cml.quantity
                lines.append({
                    'report_id': self.id,
                    'lot_id': lot.id,
                    'direction': 'backward',
                    'source_type': 'manufacturing',
                    'production_id': production.id,
                    'component_lot_id': cml.lot_id.id,
                    'product_id': cml.product_id.id,
                    'quantity': qty,
                    'uom_id': cml.product_uom_id.id,
                    'delivery_date': production.date_finished,
                })
        return lines

    def action_export_xlsx(self):
        self.ensure_one()
        return {
            'type': 'ir.actions.act_url',
            'url': '/lot_recall_report/xlsx/%s' % self.id,
            'target': 'self',
        }

    def action_view_recall_log(self):
        return {
            'type': 'ir.actions.act_window',
            'name': 'Recall Log',
            'res_model': 'lot.recall.report',
            'view_mode': 'list,form',
            'domain': [],
        }
