{
    'name': 'PDF Branding Kit',
    'version': '19.0.1.0.0',
    'category': 'Technical/Reporting',
    'summary': 'Logo, watermark and QR-code branding applied automatically across Quotation, Invoice, Delivery Slip and Purchase Order PDFs',
    'author': 'ERP23',
    'website': 'https://erp23.com',
    'support': 'erp23@brainstation-23.com',
    'license': 'OPL-1',
    'icon': '/bs_pdf_branding_kit/static/description/icon.png',
    'images': ['static/description/banner.gif'],
    'depends': ['base', 'sale', 'account', 'stock', 'purchase'],
    'data': [
        'security/ir.model.access.csv',
        'views/bs_pdf_branding_override_views.xml',
        'views/bs_pdf_branding_menus.xml',
        'views/res_config_settings_views.xml',
        'report/bs_pdf_branding_overlay.xml',
        'report/sale_report_inherit.xml',
        'report/account_move_report_inherit.xml',
        'report/stock_picking_report_inherit.xml',
        'report/purchase_order_report_inherit.xml',
    ],
    'application': False,
    'installable': True,
    'currency': 'USD',
    'price': 9.99,
    'assets': {
        'web.assets_backend': [
            'bs_pdf_branding_kit/static/src/fields/**/*',
        ],
    },
}
